"use client";
import { useEffect, useState } from "react";
type Account = { username: string; disabled: boolean }; type Social = { id: number; name: string; url: string }; type Info = Record<string, string>;
const empty: Info = { intro:"",contact:"",address:"",phone:"",facebook:"",twitter:"",socialLinks:"",links:"",landingEyebrow:"",landingTitle:"",landingAccent:"",landingLead:"",featureOneTitle:"",featureOneText:"",featureTwoTitle:"",featureTwoText:"",featureThreeTitle:"",featureThreeText:"" };
const icon = (name:string) => ({Facebook:"f",Instagram:"◎",TikTok:"♪",YouTube:"▶",Zalo:"Z",LinkedIn:"in"}[name] || "↗");
export default function OwnerClient() {
  const [accounts,setAccounts]=useState<Account[]>([]); const [info,setInfo]=useState<Info>(empty); const [socials,setSocials]=useState<Social[]>([]); const [message,setMessage]=useState("");
  async function load(){const a=await fetch("/api/owner/accounts");if(a.ok)setAccounts((await a.json()).accounts);const i=await fetch("/api/site-info");if(i.ok){const d=(await i.json()).info as Info;setInfo(d);setSocials((d.socialLinks||"").split("\n").map((line,id)=>{const [name,...parts]=line.split("|");return{id,name:name.trim(),url:parts.join("|").trim()};}).filter(x=>x.name));}}
  useEffect(()=>{void load();},[]);
  async function save(){const next={...info,socialLinks:socials.filter(s=>s.name.trim()).map(s=>`${s.name.trim()} | ${s.url.trim()}`).join("\n")};const r=await fetch("/api/site-info",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});setMessage(r.ok?"Đã lưu thông tin thành công":"Không thể lưu thông tin");}
  async function accountAction(username:string,body:object){await fetch("/api/owner/accounts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({username,...body})});await load();}
  async function logout(){await fetch("/api/owner/logout",{method:"POST"});window.location.href="/owner/login";}
  const field=(key:string,label:string,area=false)=><label className={`admin-field ${key === "facebook" || key === "twitter" ? "legacy-social-field" : ""}`}><span>{label}</span>{area?<textarea value={info[key]||""} onChange={e=>setInfo({...info,[key]:e.target.value})}/>:<input value={info[key]||""} onChange={e=>setInfo({...info,[key]:e.target.value})}/>}</label>;
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">PNN LITTLE</p><h1>Quản trị hệ thống</h1><p>Tổng số khách hàng: <strong>{accounts.length}</strong></p></div><button onClick={()=>void logout()}>Đăng xuất</button></header><section className="admin-panel owner-accounts"><h2>Tài khoản khách hàng</h2>{accounts.map(a=><div className="owner-account" key={a.username}><span className={a.disabled?"status-dot offline":"status-dot"}/><strong>{a.username}</strong><span>{a.disabled?"Đã khóa":"Đang sử dụng"}</span><button onClick={()=>void accountAction(a.username,{disabled:!a.disabled})}>{a.disabled?"Mở khóa":"Khóa"}</button><button onClick={()=>{const p=prompt("Mật khẩu mới (ít nhất 8 ký tự):");if(p)void accountAction(a.username,{password:p});}}>Đổi mật khẩu</button><button className="delete-account-button" onClick={async()=>{if(confirm(`Xóa tài khoản ${a.username}?`)){await fetch(`/api/owner/accounts?username=${encodeURIComponent(a.username)}`,{method:"DELETE"});await load();}}}>Xóa</button></div>)}</section><section className="admin-panel owner-accounts"><h2>Giới thiệu & liên hệ footer</h2>{field("intro","Giới thiệu",true)}{field("links","Liên kết nhanh (mỗi dòng một mục)",true)}{field("address","Địa chỉ")}{field("phone","Điện thoại")}{field("contact","Email")}{field("facebook","Facebook")}{field("twitter","Twitter / X")}<h3 className="owner-subtitle">Mạng xã hội</h3>{socials.map((s,i)=><div className="social-editor" key={s.id}><span className="social-icon">{icon(s.name)}</span><input placeholder="Tên mạng xã hội" value={s.name} onChange={e=>setSocials(socials.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input placeholder="https://..." value={s.url} onChange={e=>setSocials(socials.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/><button type="button" onClick={()=>setSocials(socials.filter(x=>x.id!==s.id))}>Xóa</button></div>)}<button type="button" className="add-line" onClick={()=>setSocials([...socials,{id:Date.now(),name:"",url:""}])}>+ Thêm mạng xã hội</button><h3 className="owner-subtitle">Nội dung trang giới thiệu</h3>{field("landingEyebrow","Dòng nhỏ phía trên")}{field("landingTitle","Tiêu đề chính")}{field("landingAccent","Dòng tiêu đề nổi bật")}{field("landingLead","Mô tả trang",true)}{field("featureOneTitle","Tính năng 1 - tiêu đề")}{field("featureOneText","Tính năng 1 - mô tả",true)}{field("featureTwoTitle","Tính năng 2 - tiêu đề")}{field("featureTwoText","Tính năng 2 - mô tả",true)}{field("featureThreeTitle","Tính năng 3 - tiêu đề")}{field("featureThreeText","Tính năng 3 - mô tả",true)}<button className="save-button" type="button" onClick={()=>void save()}>Lưu tất cả thay đổi</button>{message&&<p className="save-status">{message}</p>}</section></main>;
}
