"use client";
import { useEffect, useState } from "react";
export default function OwnerPasswordButton(){
 const [open,setOpen]=useState(false),[current,setCurrent]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[show,setShow]=useState(false),[signOutOthers,setSignOutOthers]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{const openPopup=()=>{setMessage("");setOpen(true);};window.addEventListener("owner-open-password",openPopup);return()=>window.removeEventListener("owner-open-password",openPopup);},[]);
 async function change(){if(password!==confirm){setMessage("Mật khẩu mới chưa khớp");return;}const r=await fetch("/api/owner/password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword:current,password,signOutOthers})});const d=await r.json();setMessage(r.ok?(signOutOthers?"Đã đổi mật khẩu — các thiết bị khác đã được đăng xuất":"Đã đổi mật khẩu và giữ nguyên các thiết bị đang đăng nhập"):(d.error||"Không thể đổi mật khẩu"));if(r.ok){setCurrent("");setPassword("");setConfirm("");}}
 const input=(label:string,value:string,set:(v:string)=>void)=><label><span>{label}</span><div className="password-input-wrap"><input type={show?"text":"password"} value={value} onChange={e=>set(e.target.value)}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Ẩn mật khẩu":"Hiện mật khẩu"}>{show?"◉":"◌"}</button></div></label>;
 if(!open)return null;
 return <div className="password-modal-backdrop" onClick={()=>setOpen(false)}><section className="admin-panel owner-password-panel password-modal" onClick={e=>e.stopPropagation()}><button type="button" className="password-modal-close" onClick={()=>setOpen(false)} aria-label="Đóng">×</button><h2>Đổi mật khẩu quản trị</h2><p>Đổi mật khẩu dùng để đăng nhập trang quản trị hệ thống.</p>{input("Mật khẩu hiện tại",current,setCurrent)}{input("Mật khẩu mới",password,setPassword)}{input("Nhập lại mật khẩu mới",confirm,setConfirm)}<label className="password-option"><input type="checkbox" checked={signOutOthers} onChange={e=>setSignOutOthers(e.target.checked)}/><span><strong>Đăng xuất khỏi tất cả thiết bị khác</strong><small>Bỏ chọn nếu muốn giữ nguyên các thiết bị đang đăng nhập.</small></span></label><button className="save-button" type="button" onClick={()=>void change()}>Đổi mật khẩu</button>{message&&<p className="save-status">{message}</p>}</section></div>;
}
